spring:
  datasource:
    url: mysql://root:YStKYznrQwOARSrxznAxTPmrdCkjmOZT@monorail.proxy.rlwy.net:45921/railway?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: YStKYznrQwOARSrxznAxTPmrdCkjmOZT

    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          CharSet: utf8
          characterEncoding: utf8
          useUnicode: true
  thymeleaf:
    cache: false
    mode: HTML
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace